---
- name: Cisco Delete and Alter Lines for Demo
  hosts: all
  gather_facts: no

  tasks:
# This is elevated enable mode, note that the other script with 'show run' works which also uses
# elevated mode..
  - name: IOS configuration *delete* lines with no parent
    when: "'Cisco' in group_names"
    ios_config:
      lines:
        - no username admin2 password 0 riverbed2
  - name: IOS configuration *alter* lines with parent
    when: "'Cisco' in group_names"
    ios_config: 
      lines:
        - switchport access vlan 152
      parents: interface GigabitEthernet0/4
# Now retrieve the file
  - name: IOS configuration backup example
    when: "'Cisco' in group_names"
    ios_config:
      backup: yes
      backup_options:
        filename: Mid-backup.txt