---
- name: Cisco Restore Config example
  hosts: all
  gather_facts: false
  connection: network_cli
  collections:
    - cisco.ios
  
  tasks:
    - action: ping

# This is elevated enable mode, note that the other script with 'show run' works which also uses
# elevated mode..
    - name: IOS configuration source example
      ios_config:
        src: "./config.txt"
