---
- name: NetIM Rollback Playbook
  hosts: localhost
  gather_facts: no

# Variables passed via JSON from Flask
# dev_name
# deviced_archive_file_path

  tasks:
  - name: NetIM Rollback Request (to Ansible REST API)
    # debug: prints to Ansible command line screen
    debug:
      msg: 
        - "NetIM Requested a Rollback for {{ dev_name }}, will retrieve the previous config file"
        - "from this NetIM path {{ deviced_archive_file_path }}"

  - name: Retrieve Rollback Config File from NetIM (to NetIM REST API)
    # debug: prints to Ansible command line screen
    debug:
      msg: "Retrieved previous config file from NetIM for {{ dev_name }}"
      
  - name: Access NetIM REST API to retrieve config file
    uri:
      # deviced_archive_file_path looks like this '/api/netim/v1/archives/281533/file'
      url: "https://10.1.150.232:8543 {{deviced_archive_file_path}} "
      method: GET
      url_username: scadmin
      url_password: R3st0nVA
      force_basic_auth: yes
      validate_certs: no
      # This forces content to be returned, if not specified and JSON is present, then JSON will be returned
      return_content: yes
      status_code: 200

    # Ansible uses register to specify a variable name and it is implicit to the output of the uri:
    register: rest_get

#  - name: Debug
    debug:
      msg: "{{ rest_get }}"

  - name: Push Previous Config File (SSH to router)
    debug:
      msg: "{{ dev_name }} roll-back was successful!"
