---
- name: NetIM Rollback Playbook
  hosts: 10.1.150.232
  gather_facts: no

# Variables passed via JSON from Flask
# dev_name
# deviced_archive_file_path

  tasks:
  - name: NetIM Rollback Request (to Ansible REST API)
    # debug: prints to Ansible command line screen
    debug:
      msg: 
        - "NetIM Requested a Rollback for {{ dev_name }}, will retrieve the previous config file"
        - "from this NetIM path {{ device_archive_file_path }}"

  - name: Retrieve Rollback Config File from NetIM (to NetIM REST API)
    # debug: prints to Ansible command line screen
    debug:
      msg: "Retrieved previous config file from NetIM for {{ dev_name }}"
      
  - name: Access NetIM REST API to retrieve config file
    uri:
      # deviced_archive_file_path looks like this '/api/netim/v1/archives/281533/file'
      url: "https://10.1.150.232:8543 {{device_archive_file_path}} "
      method: GET
      url_username: scadmin
      url_password: R3st0nVA
      force_basic_auth: yes
      validate_certs: no
      # This forces content to be returned, if not specified and JSON is present, then JSON will be returned
      return_content: yes
      status_code: 200
      # This writes the output to a file named 'config.txt'
      # Since this AWX and Docker, the actual location is in a Docker folder somewhere..
      dest: ./config.txt
    # Ansible uses register to specify a variable name and it is implicit to the output of the uri:
    # Notice it is NOT indented, at same indent level as uri:
    register: rest_get
    
  # This is debug test to see the config file text on the Ansible console screen
  - debug: 
      msg: "The output of the config file is {{lookup('file', './config.txt') }}"
  

  # I got frustrated trying to read in the file and parse with Ansible so cheating with Python..
  - name: Remove some lines from the config file (header and footer)
    script: "/usr/bin/python config_strip.py"

