---
- name: NetIM Rollback Playbook
  hosts: localhost
  gather_facts: no

# Variables passed via JSON from Flask
# dev_name
# deviced_archive_file_path

  tasks:
  - name: NetIM Rollback Request (to Ansible REST API)
    # debug: prints to Ansible command line screen
    debug:
      msg: 
        - "NetIM Requested a Rollback for {{ dev_name }}, will retrieve the previous config file"
        - "from this NetIM path {{ device_archive_file_path }}"

  - name: Retrieve Rollback Config File from NetIM (to NetIM REST API)
    # debug: prints to Ansible command line screen
    debug:
      msg: "Retrieved previous config file from NetIM for {{ dev_name }}"
      
  - name: Access NetIM REST API to retrieve config file
    url:
      # deviced_archive_file_path looks like this '/api/netim/v1/archives/281533/file'
      _terms: "https://10.1.150.232:8543 {{device_archive_file_path}} "
      method: GET
      username: scadmin
      password: R3st0nVA
      force_basic_auth: yes
      validate_certs: no
    # Ansible uses register to specify a variable name and it is implicit to the output of the uri:
    # Notice it is NOT indented, at same indent level as uri:
    register: rest_get

  # In this case, debug is NOT a custom named task, it will show up as task "debug"
  # So this is terser way to output, and just put other desired text in msg:
  - debug: 
      msg: "{{ rest_get }}"  
#  - name: Debug
#    debug:
#      msg: "{{ rest_get }}"

  - name: Push Previous Config File (SSH to router)
    debug:
      msg: "{{ dev_name }} roll-back was successful!"
